# Define our services 
services: 

  # Database -- loaded first to ensure dependenicies get met
  mysqldb:
    image: mysql:8.0
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    working_dir: /database
    # Copy our db init code over and save the database data locally 
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database/mysqldb:/var/lib/mysql
    # Default port of 3306
    ports:
      - ${DB_PORT}:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  # Main App
  smartcal_app:
    container_name: app
    build: app
    volumes:
      - ./:/app
    ports:
      - 4200:4200
    depends_on:
      - mysqldb
    # --host 0.0.0.0 to listen to all the interfaces from the container (dev env)
    command: >
      sh -c "npm install &&
             npx ng serve --host 0.0.0.0"

  # Server
  smartcal_server:
    container_name: server
    build: server
    volumes:
      - ./server:/server
    # port 3000 is default, matches to src/proxy.conf.json
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CONNECTION_LIMIT: ${DB_CONNECTION_LIMIT}
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeappservice
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - mysqldb
    networks:
      - internalnet
    command: >
      sh -c "npm i -g nodemon && npm install && nodemon ./bin/www"


# Open a tickle bridge for the containers to  eachother
networks:
  internalnet:
    driver: bridge